### ISSUE TITLE
I can't push to Github from VS Code - pop up asking to config user.name and user.email

### ISSUE THREAD

**Issue by Ahastan** [SACHSTech/ICS2O-CPT2020#1]
For some reason I cannot commit and push my test code into github from vs code.

**Comment by mrfabroa** [comment]
If you get the prompt to config your user.name and user.email.

In VS Code, at the top select Terminal -> New Terminal.  Enter the following:
```
git config user.name yourUserName
git config user.email your@Email.com
```
put your username and email accordingly in the command
