### ISSUE TITLE
Error: The key you just pressed is not recognized by SDL

### ISSUE THREAD

**Issue by Gregory-Lui** [SACHSTech/ICS2O-CPT2020#2]
whenever the program checks to see if the user presses a key. The same error message appears: "The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 8 (0), X11 KeySym 0xFF7E (Mode_switch)."
I know we covered this in Kayley's inquiry assignment but we just resorted to having any key. I need it to be a specific key.

**Comment by mrfabroa** [comment]
I advise working with pygame in VS Code instead of Repl.it to try and resolve this error.  There are too many unknowns in repl.it to try and resolve it there.
