### ISSUE TITLE
Module 'pygame' has no 'init' member

### ISSUE THREAD

**Issue by Gregory-Lui** [SACHSTech/ICS2O-CPT2020#3]
I have pygame installed on vscode and am using python 3.9.1 64-bit. However even though I use: import pygame and pygame.init none of the sub functions work properly. The pygame tab does still appear however I still get a problem while running my program.
![image](https://user-images.githubusercontent.com/75390920/104600755-6c070c00-5647-11eb-996a-b5de7969a883.png)

**Comment by mrfabroa** [comment]
See this solution https://stackoverflow.com/questions/50569453/why-does-it-say-that-module-pygame-has-no-init-member  

To open settings.json as mentioned in the solution, in VS Code go to View--> Command Palette --> type in open settings.json
